import Footer from "@/components/base/Footer";
import Header from "@/components/base/Header";
import { Metadata } from "next";


export const metadata: Metadata =
{
    title: "Home",
    description: "Generated by create next app",
};

export default function SiteLayout({
    children
}: {
    children: React.ReactNode,
}) {
    return (
        <div>
            {/* Header */}
            <Header />
            {/* Body */}
            {children}
            {/* Footer */}
            <Footer />
        </div>
    )
}