import type { Metadata } from "next";
import { Khmer, Poppins } from "next/font/google";
import "./globals.css";

const khmer = Khmer({
  subsets: ["khmer"],
  weight: ['400'],
  variable: '--khmer',
});
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--poppins',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${khmer.className} ${khmer.variable} ${poppins.variable}`}>
        {children}
      </body>
    </html>
  );
}
